# Jekyll configuration for GitHub Pages
title: "Earnings Call Tone Dispersion Research"
description: "A quantitative analysis of tone dispersion in earnings calls and its predictive power for stock returns"
baseurl: ""
url: "https://kurry.github.io/earnings_call_tone_research"

# Theme
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - methodology.md
  - results.md
  - technical.md

# Settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Exclude from processing
exclude:
  - README.md
  - docs_README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - src/
  - tests/
  - data/
  - outputs/
  - venv/
  - "*.py"
  - "*.txt"
  - "*.parquet"

# Google Analytics (optional)

# Author
author:
  name: "Kurry Tran"
  email: "kurry.tran@gmail.com"

# Social links
github_username: kurry

# Build settings
future: false
unpublished: false
safe: true